mainTabAbout <- tabPanel(
    "About",
    tabsetPanel(
    id = "aboutTab", type = "pills",
    tabPanel("PK Model"),
    tabPanel("Shiny App")
    ), 
    br(),
    tabPanel(
      "PK Model",
      conditionalPanel(
        condition = "input.aboutTab == 'PK Model'",
        h2("Objective"),
        h4("To visualize and explore the Bedaquiline and M2 Pharmacokinetic Model developed by Svensson et al. by modifying the parameter values in the dose regimen."),
        br(),
        h2("Structural Model"),
        imageOutput("img1"),
        h4("Schematic Illustration of Structural Model"),
        br(),
        h2("Summary of Model Characteristics"),
        p("The data used to develop model were obtained from two phase IIb studies called C208 and C209 (TMC207-C208, ClinicalTrials.gov number NCT00449644 and TMC207-C209, ClinicalTrials.gov number NCT00910871) shared to the PreDiCT-TB consortium"),
        p("It is a Nonlinear mixed-effects models consisting of structural components describing the typical PK characteristics and stochastic components describing the random variability in the population were utilized."),
        p("The typical PK characteristics was modelled from Data from 335 patients (23 from study C208 stage 1, 79 from study C208 stage 2, and 233 from study C209)  with MDR-TB receiving 24 weeks of bedaquiline on top of a longer individualized background regimen"),
        p("Bedaquiiline  absorption was described with two transit compartments and Estimated parameters were the mean absorption time (MAT; i.e., typical time to 90% complete absorption) and the fraction of MAT, which consisted of delay in the transit compartments or first-order absorption, respectively"),
        p("Bedaquiline and M2 disposition were well described by three and one-compartment models, respectively. bedaquiline and one and two-compartment models for M2. The typical values for bioavailability (F) and the fraction of bedaquiline metabolized to M2 (fm) were fixed to one, hence, the disposition parameters estimated were relative to F for bedaquiline and relative to F times fm for M2"),
        p("Semiphysiological models were developed to characterize the changes in weight and albumin over time. Weight and albumin were correlated, typically increasing after the start of treatment, and significantly affected bedaquiline and M2 plasma disposition"),
        p("Age and race were significant covariates, whereas concomitant human immunodeficiency virus (HIV) infection, sex, or having extensively drug-resistant TB was not"),
        p("Increasing age was found to decrease CL of bedaquiline and M2 linearly with 0.9% (95% CI 5 0.8–1.0%) per year and patients of black race were estimated to have 84% (95% CI 5 75–94%) higher typical CL of bedaquiline and M2 compared to non-black subjects. This was the first population model simultaneously characterizing bedaquiline and M2 PKs in its intended use population."),
        p("The developed model has been used for efficacy and safety exposure-response analyses in different studies"),
        br(),
        h3("Reference"),
        p("E. M. Svensson, A. G. Dosne, and M. O. Karlsson, ‘Population Pharmacokinetics of Bedaquiline and Metabolite M2 in Patients with Drug-Resistant Tuberculosis: The Effect of Time-Varying Weight and Albumin’, CPT Pharmacometrics Syst Pharmacol, vol. 5, no. 12, pp. 682–691, Dec. 2016, doi: 10.1002/PSP4.12147."),
        br()
      )
    ),
    tabPanel(
      "Shiny App",
      conditionalPanel(
        condition = "input.aboutTab == 'Shiny App'",
        h2("How to use shiny app"),
        h4("1. Select the navigation bar"),
        h5("*Select Dosing navigation bar for one dose regimen"),
        h5("*Select Multiple Regimen navigation bar for three dose regimen"),
        br(),
        h4("2. Select the Dosing Details tab"),
        h4("Define the dosing details in the tab input"),
        br(),
        h4("Add a loading dose if desired"),
        h4("Define the loading dose details in the tab input"),
        p("*Loading dose"),
        p("*Loading dose duration (days or weeks)"),
        p("*Loading dose interval"),
        p("*Loading dose frequency (once daily, twice daily, three times weekly, once weekly"),
        br(),
        h4("Define the Maintenance dose details in the tab input"),
        p("*Maintenance dose"),
        p("*Maintenance dose duration (days or weeks)"),
        p("*Maintenance dose interval"),
        p("*Maintenance dose frequency"),
        br(),
        h4("3.Select the Model Covariates tab"),
        h4("Define the model covariates values in the tab input"),
        p("*Age"),
        p("*Race Effect"),
        p("*Baseline Body Weight (kg)"),
        p("*Baseline Albumin Concentration (g/dL)"),
        br(),
        h4("4. Select the Concomitant medication tab"),
        h4("Choose a Concomitant medication effect"),
        p("*None"),
        p("*Efavirenz"),
        p("*Nevirapine"),
        p("*Lopinavir/r"),
        p("*Rifampicin"),
        p("*Rifapentine"),
        br(),
        h4("5. Select the Simulation Setting tab"),
        h4("Define the simulation output"),
        p("*Number of simulated individuals"),
        p("*Simulation time"),
        p("*Interindiviual variability"),
        br(),
        h4("Choose plot output from radiobuttons"),
        p("*Full Concentration Curve"),
        p("*Trough Concentration Curve"),
        p("*Mean Daily Concentration Curve"),
        p("*Mean Weekly Concentration Curve"),
        p("*Body Weight & Albumin Concentration"),
        br(),
        h4("**if you select the multiple regimen navigation bar, you will perform step 1 to 5 for three dosing regimen**")
      )
    )
  )
